### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [gabrieluizramos/dotfiles#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`.brew`](https://github.com/gabrieluizramos/dotfiles/blob/1b68bda39498ed54b98dadc1e41c1a7c74ffa58b/config/.brew). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by gabrieluizramos** [comment]
Hi @reitermarkus , thank you very much! Just updated the link right now!

Thank you!
